#!/usr/bin/env python3
"""Split app/raffi_module.js into ordered chunks and emit SQL that loads them into
public.raffi_module_chunks (served by the raffi-module edge function).

Usage:
    python3 scripts/build_module_chunks.py            # writes sql/load_module_chunks.sql
    python3 scripts/build_module_chunks.py --check    # print per-chunk sha256 + total, no write

The chunks split on line boundaries (~16 KB each) so each INSERT stays well under
SQL editor/API limits. The generated SQL uses a dollar-quoted string with the tag
$rjq$ — the module source must never contain the literal $rjq$ (asserted below).

Verify after loading:  GET https://<project>.supabase.co/functions/v1/raffi-module/version
The reported sha256 must equal the total printed by this script.
"""
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "app" / "raffi_module.js"
OUT = ROOT / "sql" / "load_module_chunks.sql"
TAG = "$rjq$"
TARGET = 16_000  # bytes per chunk (line-aligned)


def split_chunks(data: bytes) -> list[bytes]:
    lines = data.split(b"\n")
    parts: list[bytes] = []
    cur = b""
    for i, line in enumerate(lines):
        piece = line + (b"\n" if i < len(lines) - 1 else b"")
        if len(cur) + len(piece) > TARGET and cur:
            parts.append(cur)
            cur = b""
        cur += piece
    if cur:
        parts.append(cur)
    assert b"".join(parts) == data
    return parts


def main() -> None:
    data = SRC.read_bytes()
    text = data.decode("utf-8")
    assert TAG not in text, f"module source must not contain {TAG!r}"
    parts = split_chunks(data)
    total_sha = hashlib.sha256(data).hexdigest()
    print(f"{SRC.name}: {len(data)} bytes, {len(parts)} chunks, sha256 {total_sha}")
    for i, p in enumerate(parts, 1):
        print(f"  chunk {i}: {len(p)} bytes sha256 {hashlib.sha256(p).hexdigest()}")
    if "--check" in sys.argv:
        return
    stmts = ["-- Generated by scripts/build_module_chunks.py — do not edit by hand.",
             f"-- Source: app/raffi_module.js ({len(data)} bytes, sha256 {total_sha})",
             "begin;", "delete from public.raffi_module_chunks;"]
    for i, p in enumerate(parts, 1):
        body = p.decode("utf-8")
        stmts.append(
            f"insert into public.raffi_module_chunks(seq, body) values ({i}, {TAG}{body}{TAG});"
        )
    stmts.append("commit;")
    stmts.append(
        "select count(*) as chunks, sum(octet_length(body)) as bytes,\n"
        "       encode(sha256(convert_to(string_agg(body,'' order by seq),'UTF8')),'hex') as sha256\n"
        "from public.raffi_module_chunks;"
    )
    OUT.write_text("\n".join(stmts) + "\n", encoding="utf-8")
    print(f"wrote {OUT} — run it in the Supabase SQL editor, then verify /raffi-module/version sha256 == {total_sha}")


if __name__ == "__main__":
    main()
